// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`uid`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, uid string) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, uid string) error
	}

	defaultUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	User struct {
		Uid          string       `db:"uid"`
		PasswordHash string       `db:"password_hash"`
		Name         string       `db:"name"`
		Avatar       string       `db:"avatar"`
		Gender       uint64       `db:"gender"` // 0=未知, 1=男, 2=女
		Birthday     sql.NullTime `db:"birthday"`
		Signature    string       `db:"signature"`
		Phone        string       `db:"phone"`
		Email        string       `db:"email"`
		LastIp       string       `db:"last_ip"`
		Status       uint64       `db:"status"` // 0=离线, 1=在线, 2=隐身
		LastSeenAt   sql.NullTime `db:"last_seen_at"`
		CreatedAt    time.Time    `db:"created_at"`
		UpdatedAt    time.Time    `db:"updated_at"`
	}
)

func newUserModel(conn sqlx.SqlConn) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: "`user`",
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, uid string) error {
	query := fmt.Sprintf("delete from %s where `uid` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, uid)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, uid string) (*User, error) {
	query := fmt.Sprintf("select %s from %s where `uid` = ? limit 1", userRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, uid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uid, data.PasswordHash, data.Name, data.Avatar, data.Gender, data.Birthday, data.Signature, data.Phone, data.Email, data.LastIp, data.Status, data.LastSeenAt)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, data *User) error {
	query := fmt.Sprintf("update %s set %s where `uid` = ?", m.table, userRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.PasswordHash, data.Name, data.Avatar, data.Gender, data.Birthday, data.Signature, data.Phone, data.Email, data.LastIp, data.Status, data.LastSeenAt, data.Uid)
	return err
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
