http_address: 127.0.0.1
http_port: 8080
tcp_address: 127.0.0.1
tcp_port: 9000
data_source: "root:1234@tcp(127.0.0.1:3306)/AIm?parseTime=true&loc=UTC"
mongo_uri: "mongodb://127.0.0.1:27017"
mongo_db: "im"
redis_addr: "192.168.116.130:6379"
redis_password: "1234"
redis_db: 0
rabbitmq_url: "amqp://guest:guest@127.0.0.1:5672/"
log_path: "logs/im.log"
log_level: "info"
gateway_port: 8000
jwt_secret: "change-me-in-production"
backend_addrs:
  - "127.0.0.1:9000"
  - "127.0.0.1:9001"