// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService 通过 Go 侧调用后端 HTTP REST API（:8080），
 * 避免 WebView 跨域问题。前端通过绑定调用这些方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangePassword 修改密码。
 * @param {string} token
 * @param {string} oldPassword
 * @param {string} newPassword
 * @returns {$CancellablePromise<void>}
 */
export function ChangePassword(token, oldPassword, newPassword) {
    return $Call.ByID(2925615738, token, oldPassword, newPassword);
}

/**
 * GetConversations 获取会话列表（最近联系人）。
 * @param {string} token
 * @returns {$CancellablePromise<$models.ConversationInfo[]>}
 */
export function GetConversations(token) {
    return $Call.ByID(2281367027, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetFriends 获取好友列表。
 * @param {string} token
 * @returns {$CancellablePromise<$models.FriendInfo[]>}
 */
export function GetFriends(token) {
    return $Call.ByID(3765766454, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetProfile 获取当前登录用户资料。
 * @param {string} token
 * @returns {$CancellablePromise<$models.Profile | null>}
 */
export function GetProfile(token) {
    return $Call.ByID(588788746, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Login 使用 uid + 密码登录，返回 JWT token。
 * @param {string} uid
 * @param {string} password
 * @returns {$CancellablePromise<$models.LoginResult | null>}
 */
export function Login(uid, password) {
    return $Call.ByID(655276660, uid, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Register 注册新用户，返回分配的 uid。
 * @param {string} name
 * @param {string} password
 * @param {string} email
 * @param {string} phone
 * @returns {$CancellablePromise<$models.RegisterResult | null>}
 */
export function Register(name, password, email, phone) {
    return $Call.ByID(3233095442, name, password, email, phone).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * SetBaseURL 允许前端覆盖后端地址。
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function SetBaseURL(url) {
    return $Call.ByID(846328329, url);
}

/**
 * UpdateProfile 更新用户资料。
 * @param {string} token
 * @param {$models.Profile} p
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProfile(token, p) {
    return $Call.ByID(2043013171, token, p);
}

// Private type creation functions
const $$createType0 = $models.ConversationInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.FriendInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.Profile.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.LoginResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.RegisterResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
