// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService 通过 Go 侧调用后端 HTTP REST API（:8080），
 * 避免 WebView 跨域问题。前端通过绑定调用这些方法。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChangePassword 修改密码。
 * @param {string} token
 * @param {string} oldPassword
 * @param {string} newPassword
 * @returns {$CancellablePromise<void>}
 */
export function ChangePassword(token, oldPassword, newPassword) {
    return $Call.ByID(2925615738, token, oldPassword, newPassword);
}

/**
 * FriendAccept 接受好友申请。
 * @param {string} token
 * @param {string} friendUid
 * @returns {$CancellablePromise<void>}
 */
export function FriendAccept(token, friendUid) {
    return $Call.ByID(2419095335, token, friendUid);
}

/**
 * FriendBlock 把对方加入黑名单。
 * @param {string} token
 * @param {string} friendUid
 * @returns {$CancellablePromise<void>}
 */
export function FriendBlock(token, friendUid) {
    return $Call.ByID(2040996604, token, friendUid);
}

/**
 * FriendBlockList 获取黑名单列表。
 * @param {string} token
 * @returns {$CancellablePromise<$models.FriendInfo[]>}
 */
export function FriendBlockList(token) {
    return $Call.ByID(962965124, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * FriendRemove 删除好友。
 * @param {string} token
 * @param {string} friendUid
 * @returns {$CancellablePromise<void>}
 */
export function FriendRemove(token, friendUid) {
    return $Call.ByID(960749231, token, friendUid);
}

/**
 * FriendRequest 向对方发起好友申请。
 * @param {string} token
 * @param {string} friendUid
 * @param {string} remark
 * @returns {$CancellablePromise<void>}
 */
export function FriendRequest(token, friendUid, remark) {
    return $Call.ByID(291820476, token, friendUid, remark);
}

/**
 * FriendRequests 获取收到的好友申请列表。
 * @param {string} token
 * @returns {$CancellablePromise<$models.FriendRequestInfo[]>}
 */
export function FriendRequests(token) {
    return $Call.ByID(817458909, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * FriendUnblock 把对方移出黑名单。
 * @param {string} token
 * @param {string} friendUid
 * @returns {$CancellablePromise<void>}
 */
export function FriendUnblock(token, friendUid) {
    return $Call.ByID(4102095133, token, friendUid);
}

/**
 * GetAvatar 按 _id 读取头像，返回可直接用于 <img src> 的 data URL（无图返回空串）。
 * @param {string} token
 * @param {string} id
 * @returns {$CancellablePromise<string>}
 */
export function GetAvatar(token, id) {
    return $Call.ByID(1717403080, token, id);
}

/**
 * GetAvatarByUid 按用户 uid 解析头像，返回可直接用于 <img src> 的 data URL（无头像返回空串）。
 * @param {string} token
 * @param {string} uid
 * @returns {$CancellablePromise<string>}
 */
export function GetAvatarByUid(token, uid) {
    return $Call.ByID(3460249453, token, uid);
}

/**
 * GetChatHistory 分页拉取历史消息。peer 与 group 二选一；before 为 unix 毫秒游标（0 表示最新一页）。
 * @param {string} token
 * @param {string} peer
 * @param {string} group
 * @param {number} before
 * @param {number} limit
 * @returns {$CancellablePromise<$models.HistoryMessageInfo[]>}
 */
export function GetChatHistory(token, peer, group, before, limit) {
    return $Call.ByID(2265014521, token, peer, group, before, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetConversations 获取会话列表（最近联系人）。
 * @param {string} token
 * @returns {$CancellablePromise<$models.ConversationInfo[]>}
 */
export function GetConversations(token) {
    return $Call.ByID(2281367027, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetFriends 获取好友列表。
 * @param {string} token
 * @returns {$CancellablePromise<$models.FriendInfo[]>}
 */
export function GetFriends(token) {
    return $Call.ByID(3765766454, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetProfile 获取当前登录用户资料。
 * @param {string} token
 * @returns {$CancellablePromise<$models.Profile | null>}
 */
export function GetProfile(token) {
    return $Call.ByID(588788746, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GroupAnnounce 设置群公告（群主/管理员）。
 * @param {string} token
 * @param {string} groupId
 * @param {string} announcement
 * @returns {$CancellablePromise<void>}
 */
export function GroupAnnounce(token, groupId, announcement) {
    return $Call.ByID(4074391765, token, groupId, announcement);
}

/**
 * GroupApprove 群主通过入群申请。
 * @param {string} token
 * @param {string} groupId
 * @param {string} applicantUid
 * @returns {$CancellablePromise<void>}
 */
export function GroupApprove(token, groupId, applicantUid) {
    return $Call.ByID(3716494831, token, groupId, applicantUid);
}

/**
 * GroupCreate 创建群组（创建者自动成为群主成员）。
 * @param {string} token
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<$models.GroupBrief | null>}
 */
export function GroupCreate(token, name, description) {
    return $Call.ByID(390833698, token, name, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GroupDisband 解散群（仅群主）。
 * @param {string} token
 * @param {string} groupId
 * @returns {$CancellablePromise<void>}
 */
export function GroupDisband(token, groupId) {
    return $Call.ByID(1346376785, token, groupId);
}

/**
 * GroupInfo 获取群资料（含群公告）。
 * @param {string} token
 * @param {string} groupId
 * @returns {$CancellablePromise<$models.GroupInfoData | null>}
 */
export function GroupInfo(token, groupId) {
    return $Call.ByID(1336094710, token, groupId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GroupInvite 邀请好友入群（仅群成员可邀请）。
 * @param {string} token
 * @param {string} groupId
 * @param {string} friendUid
 * @returns {$CancellablePromise<void>}
 */
export function GroupInvite(token, groupId, friendUid) {
    return $Call.ByID(1297826583, token, groupId, friendUid);
}

/**
 * GroupJoin 加入群组。
 * @param {string} token
 * @param {string} groupId
 * @returns {$CancellablePromise<void>}
 */
export function GroupJoin(token, groupId) {
    return $Call.ByID(1985800850, token, groupId);
}

/**
 * GroupJoinRequests 群主查看某群的待审批入群申请。
 * @param {string} token
 * @param {string} groupId
 * @returns {$CancellablePromise<$models.GroupJoinRequestInfo[]>}
 */
export function GroupJoinRequests(token, groupId) {
    return $Call.ByID(1442796164, token, groupId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GroupKick 踢出群成员（群主/管理员）。
 * @param {string} token
 * @param {string} groupId
 * @param {string} targetUid
 * @returns {$CancellablePromise<void>}
 */
export function GroupKick(token, groupId, targetUid) {
    return $Call.ByID(1309848624, token, groupId, targetUid);
}

/**
 * GroupLeave 退出群聊（群主不可退，需先转让或解散）。
 * @param {string} token
 * @param {string} groupId
 * @returns {$CancellablePromise<void>}
 */
export function GroupLeave(token, groupId) {
    return $Call.ByID(1243942949, token, groupId);
}

/**
 * GroupList 获取我加入的群列表。
 * @param {string} token
 * @returns {$CancellablePromise<$models.GroupBrief[]>}
 */
export function GroupList(token) {
    return $Call.ByID(2313833298, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GroupMembers 获取群成员列表。
 * @param {string} token
 * @param {string} groupId
 * @returns {$CancellablePromise<$models.GroupMemberInfo[]>}
 */
export function GroupMembers(token, groupId) {
    return $Call.ByID(943058937, token, groupId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GroupMute 禁言/解除禁言成员（minutes<=0 表示解除）。
 * @param {string} token
 * @param {string} groupId
 * @param {string} targetUid
 * @param {number} minutes
 * @returns {$CancellablePromise<void>}
 */
export function GroupMute(token, groupId, targetUid, minutes) {
    return $Call.ByID(2072074103, token, groupId, targetUid, minutes);
}

/**
 * GroupReject 群主拒绝入群申请。
 * @param {string} token
 * @param {string} groupId
 * @param {string} applicantUid
 * @returns {$CancellablePromise<void>}
 */
export function GroupReject(token, groupId, applicantUid) {
    return $Call.ByID(732758453, token, groupId, applicantUid);
}

/**
 * GroupTransfer 转让群主（仅群主）。
 * @param {string} token
 * @param {string} groupId
 * @param {string} targetUid
 * @returns {$CancellablePromise<void>}
 */
export function GroupTransfer(token, groupId, targetUid) {
    return $Call.ByID(1445377293, token, groupId, targetUid);
}

/**
 * Login 使用 uid + 密码登录，返回 JWT token。
 * @param {string} uid
 * @param {string} password
 * @returns {$CancellablePromise<$models.LoginResult | null>}
 */
export function Login(uid, password) {
    return $Call.ByID(655276660, uid, password).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * MessageRecall 撤回自己的消息。
 * @param {string} token
 * @param {string} msgId
 * @returns {$CancellablePromise<void>}
 */
export function MessageRecall(token, msgId) {
    return $Call.ByID(2217445827, token, msgId);
}

/**
 * MomentComment 评论动态。
 * @param {string} token
 * @param {string} momentId
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function MomentComment(token, momentId, content) {
    return $Call.ByID(487229832, token, momentId, content);
}

/**
 * MomentDelete 删除自己的动态。
 * @param {string} token
 * @param {string} momentId
 * @returns {$CancellablePromise<void>}
 */
export function MomentDelete(token, momentId) {
    return $Call.ByID(4235253532, token, momentId);
}

/**
 * MomentLike 切换点赞，返回切换后的状态。
 * @param {string} token
 * @param {string} momentId
 * @returns {$CancellablePromise<boolean>}
 */
export function MomentLike(token, momentId) {
    return $Call.ByID(3480998972, token, momentId);
}

/**
 * MomentPublish 发布朋友圈动态。images 为图片 data URL 列表。
 * @param {string} token
 * @param {string} content
 * @param {string[]} images
 * @returns {$CancellablePromise<$models.MomentInfo | null>}
 */
export function MomentPublish(token, content, images) {
    return $Call.ByID(2613901478, token, content, images).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * MomentTimeline 获取朋友圈时间线（自己 + 好友）。
 * @param {string} token
 * @returns {$CancellablePromise<$models.MomentInfo[]>}
 */
export function MomentTimeline(token) {
    return $Call.ByID(2506335140, token).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * Register 注册新用户，返回分配的 uid。
 * @param {string} name
 * @param {string} password
 * @param {string} email
 * @param {string} phone
 * @returns {$CancellablePromise<$models.RegisterResult | null>}
 */
export function Register(name, password, email, phone) {
    return $Call.ByID(3233095442, name, password, email, phone).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType25($result);
    }));
}

/**
 * SetBaseURL 允许前端覆盖后端地址。
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function SetBaseURL(url) {
    return $Call.ByID(846328329, url);
}

/**
 * UpdateProfile 更新用户资料。
 * @param {string} token
 * @param {$models.Profile} p
 * @returns {$CancellablePromise<void>}
 */
export function UpdateProfile(token, p) {
    return $Call.ByID(2043013171, token, p);
}

/**
 * UploadAvatar 上传头像（base64 图片），存 MongoDB 并更新 MySQL，返回图片 _id。
 * @param {string} token
 * @param {string} dataBase64
 * @param {string} contentType
 * @returns {$CancellablePromise<string>}
 */
export function UploadAvatar(token, dataBase64, contentType) {
    return $Call.ByID(1054061075, token, dataBase64, contentType);
}

/**
 * UploadFile 上传任意文件（base64），返回 file_id（复用通用二进制存储，下载经 /api/avatar?id=）。
 * @param {string} token
 * @param {string} dataBase64
 * @param {string} contentType
 * @returns {$CancellablePromise<string>}
 */
export function UploadFile(token, dataBase64, contentType) {
    return $Call.ByID(1532823780, token, dataBase64, contentType);
}

/**
 * UserInfo 按 uid 查询用户公开信息（搜索添加好友前预览）。
 * @param {string} token
 * @param {string} uid
 * @returns {$CancellablePromise<$models.UserBriefInfo | null>}
 */
export function UserInfo(token, uid) {
    return $Call.ByID(3553672432, token, uid).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.FriendInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.FriendRequestInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.HistoryMessageInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.ConversationInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.Profile.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.GroupBrief.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $models.GroupInfoData.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $models.GroupJoinRequestInfo.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $Create.Array($$createType10);
const $$createType17 = $models.GroupMemberInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $models.LoginResult.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = $models.MomentInfo.createFrom;
const $$createType22 = $Create.Nullable($$createType21);
const $$createType23 = $Create.Array($$createType21);
const $$createType24 = $models.RegisterResult.createFrom;
const $$createType25 = $Create.Nullable($$createType24);
const $$createType26 = $models.UserBriefInfo.createFrom;
const $$createType27 = $Create.Nullable($$createType26);
