// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 是前端与后端 TCP 长连接之间的桥接层。
 * 前端通过绑定调用其方法收发实时消息，后端推送的消息以事件形式发给前端。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * Auth 发送 JWT 认证帧。
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function Auth(token) {
    return $Call.ByID(2797524893, token);
}

/**
 * Connect 拨号连接后端 TCP 服务（网关 :8000 或直连 :9000）。
 * @param {string} addr
 * @returns {$CancellablePromise<void>}
 */
export function Connect(addr) {
    return $Call.ByID(2277870775, addr);
}

/**
 * Disconnect 主动断开连接。
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(3488307849);
}

/**
 * SendGroupText 发送群聊文本消息，body 为 {group_id, content} 的 JSON。
 * @param {string} groupId
 * @param {string} content
 * @returns {$CancellablePromise<number>}
 */
export function SendGroupText(groupId, content) {
    return $Call.ByID(1370575323, groupId, content);
}

/**
 * SendText 发送单聊文本消息，body 为 {to_uid, content} 的 JSON。
 * 返回本条消息的 key，前端可用其匹配后续的 ack/nack。
 * @param {string} toUid
 * @param {string} content
 * @returns {$CancellablePromise<number>}
 */
export function SendText(toUid, content) {
    return $Call.ByID(1246534766, toUid, content);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(893176384, app);
}

/**
 * Sync 触发离线消息同步（发送 Json 帧）。
 * @returns {$CancellablePromise<void>}
 */
export function Sync() {
    return $Call.ByID(1990654196);
}
