// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalStore 用纯 Go SQLite 在本地持久化登录态与收发消息：
 *   - session.db：当前登录态（token/uid/name/profile），替代 localStorage。
 *   - messages_<uid>.db：按账号分库的消息历史。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearMessages removes local cached messages for one conversation only.
 * @param {string} peer
 * @returns {$CancellablePromise<void>}
 */
export function ClearMessages(peer) {
    return $Call.ByID(3727948057, peer);
}
/**
 * ClearSession 登出时清除登录态。
 * @returns {$CancellablePromise<void>}
 */
export function ClearSession() {
    return $Call.ByID(3891942395);
}

/**
 * Init 打开（或创建）当前账号的本地消息库并建表。
 * @param {string} selfUid
 * @returns {$CancellablePromise<void>}
 */
export function Init(selfUid) {
    return $Call.ByID(794562406, selfUid);
}

/**
 * LoadMessages 按会话加载最近 limit 条消息（时间升序）。
 * @param {string} peer
 * @param {number} limit
 * @returns {$CancellablePromise<$models.LocalMessage[]>}
 */
export function LoadMessages(peer, limit) {
    return $Call.ByID(2672725732, peer, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * LoadSession 读取当前登录态（无则返回空 Session）。
 * @returns {$CancellablePromise<$models.Session | null>}
 */
export function LoadSession() {
    return $Call.ByID(3492567636).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * MarkRecalled 将本地某条消息标记为已撤回（按 msg_id 定位），使撤回状态在重启后仍生效。
 * @param {string} msgId
 * @returns {$CancellablePromise<void>}
 */
export function MarkRecalled(msgId) {
    return $Call.ByID(51041097, msgId);
}

/**
 * SaveMessage 持久化一条消息。
 * @param {string} peer
 * @param {string} msgId
 * @param {string} fromUid
 * @param {string} content
 * @param {boolean} self
 * @param {string} status
 * @param {number} ts
 * @returns {$CancellablePromise<void>}
 */
export function SaveMessage(peer, msgId, fromUid, content, self, status, ts) {
    return $Call.ByID(183906840, peer, msgId, fromUid, content, self, status, ts);
}

/**
 * SaveSession 持久化登录态。
 * @param {string} token
 * @param {string} uid
 * @param {string} name
 * @param {string} profile
 * @returns {$CancellablePromise<void>}
 */
export function SaveSession(token, uid, name, profile) {
    return $Call.ByID(470146979, token, uid, name, profile);
}


/**
 * SearchMessages searches local messages in one conversation by keyword, newest first.
 * @param {string} peer
 * @param {string} keyword
 * @param {number} limit
 * @returns {$CancellablePromise<$models.LocalMessage[]>}
 */
export function SearchMessages(peer, keyword, limit) {
    return $Call.ByID(3405892884, peer, keyword, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}
// Private type creation functions
const $$createType0 = $models.LocalMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Session.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
