// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LocalStore 用纯 Go SQLite 在本地持久化收发的消息，支持离线/历史加载。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Init 打开（或创建）当前账号的本地消息库并建表。按 selfUid 分库，避免多账号混淆。
 * @param {string} selfUid
 * @returns {$CancellablePromise<void>}
 */
export function Init(selfUid) {
    return $Call.ByID(794562406, selfUid);
}

/**
 * LoadMessages 按会话加载最近 limit 条消息（时间升序）。
 * @param {string} peer
 * @param {number} limit
 * @returns {$CancellablePromise<$models.LocalMessage[]>}
 */
export function LoadMessages(peer, limit) {
    return $Call.ByID(2672725732, peer, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * SaveMessage 持久化一条消息。
 * @param {string} peer
 * @param {string} msgId
 * @param {string} fromUid
 * @param {string} content
 * @param {boolean} self
 * @param {string} status
 * @param {number} ts
 * @returns {$CancellablePromise<void>}
 */
export function SaveMessage(peer, msgId, fromUid, content, self, status, ts) {
    return $Call.ByID(183906840, peer, msgId, fromUid, content, self, status, ts);
}

// Private type creation functions
const $$createType0 = $models.LocalMessage.createFrom;
const $$createType1 = $Create.Array($$createType0);
