// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ConversationInfo {
    /**
     * Creates a new ConversationInfo instance.
     * @param {Partial<ConversationInfo>} [$$source = {}] - The source object to create the ConversationInfo.
     */
    constructor($$source = {}) {
        if (!("peer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["peer"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConversationInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConversationInfo(/** @type {Partial<ConversationInfo>} */($$parsedSource));
    }
}

export class FriendInfo {
    /**
     * Creates a new FriendInfo instance.
     * @param {Partial<FriendInfo>} [$$source = {}] - The source object to create the FriendInfo.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("remark" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("avatar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FriendInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FriendInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FriendInfo(/** @type {Partial<FriendInfo>} */($$parsedSource));
    }
}

export class FriendRequestInfo {
    /**
     * Creates a new FriendRequestInfo instance.
     * @param {Partial<FriendRequestInfo>} [$$source = {}] - The source object to create the FriendRequestInfo.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * 申请人
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("friend_uid" in $$source)) {
            /**
             * 接收方（我）
             * @member
             * @type {string}
             */
            this["friend_uid"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("remark" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remark"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FriendRequestInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FriendRequestInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FriendRequestInfo(/** @type {Partial<FriendRequestInfo>} */($$parsedSource));
    }
}

export class GroupBrief {
    /**
     * Creates a new GroupBrief instance.
     * @param {Partial<GroupBrief>} [$$source = {}] - The source object to create the GroupBrief.
     */
    constructor($$source = {}) {
        if (!("group_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupBrief instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupBrief}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupBrief(/** @type {Partial<GroupBrief>} */($$parsedSource));
    }
}

export class GroupInfoData {
    /**
     * Creates a new GroupInfoData instance.
     * @param {Partial<GroupInfoData>} [$$source = {}] - The source object to create the GroupInfoData.
     */
    constructor($$source = {}) {
        if (!("group_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group_id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("owner_uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["owner_uid"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("announcement" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["announcement"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupInfoData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupInfoData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupInfoData(/** @type {Partial<GroupInfoData>} */($$parsedSource));
    }
}

export class GroupJoinRequestInfo {
    /**
     * Creates a new GroupJoinRequestInfo instance.
     * @param {Partial<GroupJoinRequestInfo>} [$$source = {}] - The source object to create the GroupJoinRequestInfo.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("group_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group_id"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupJoinRequestInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupJoinRequestInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupJoinRequestInfo(/** @type {Partial<GroupJoinRequestInfo>} */($$parsedSource));
    }
}

export class GroupMemberInfo {
    /**
     * Creates a new GroupMemberInfo instance.
     * @param {Partial<GroupMemberInfo>} [$$source = {}] - The source object to create the GroupMemberInfo.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["role"] = 0;
        }
        if (!("nickname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nickname"] = "";
        }
        if (!("mute_until" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mute_until"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GroupMemberInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GroupMemberInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GroupMemberInfo(/** @type {Partial<GroupMemberInfo>} */($$parsedSource));
    }
}

export class HistoryMessageInfo {
    /**
     * Creates a new HistoryMessageInfo instance.
     * @param {Partial<HistoryMessageInfo>} [$$source = {}] - The source object to create the HistoryMessageInfo.
     */
    constructor($$source = {}) {
        if (!("msg_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["msg_id"] = "";
        }
        if (!("from_uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from_uid"] = "";
        }
        if (!("to_uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["to_uid"] = "";
        }
        if (!("group_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group_id"] = "";
        }
        if (!("msg_type" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["msg_type"] = 0;
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryMessageInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryMessageInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryMessageInfo(/** @type {Partial<HistoryMessageInfo>} */($$parsedSource));
    }
}

export class LocalMessage {
    /**
     * Creates a new LocalMessage instance.
     * @param {Partial<LocalMessage>} [$$source = {}] - The source object to create the LocalMessage.
     */
    constructor($$source = {}) {
        if (!("msg_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["msg_id"] = "";
        }
        if (!("from_uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["from_uid"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("self" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["self"] = false;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("ts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ts"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalMessage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalMessage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalMessage(/** @type {Partial<LocalMessage>} */($$parsedSource));
    }
}

export class LoginResult {
    /**
     * Creates a new LoginResult instance.
     * @param {Partial<LoginResult>} [$$source = {}] - The source object to create the LoginResult.
     */
    constructor($$source = {}) {
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoginResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginResult(/** @type {Partial<LoginResult>} */($$parsedSource));
    }
}

export class MomentCommentInfo {
    /**
     * Creates a new MomentCommentInfo instance.
     * @param {Partial<MomentCommentInfo>} [$$source = {}] - The source object to create the MomentCommentInfo.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MomentCommentInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MomentCommentInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MomentCommentInfo(/** @type {Partial<MomentCommentInfo>} */($$parsedSource));
    }
}

export class MomentInfo {
    /**
     * Creates a new MomentInfo instance.
     * @param {Partial<MomentInfo>} [$$source = {}] - The source object to create the MomentInfo.
     */
    constructor($$source = {}) {
        if (!("moment_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["moment_id"] = "";
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("images" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["images"] = [];
        }
        if (!("likes" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["likes"] = [];
        }
        if (!("comments" in $$source)) {
            /**
             * @member
             * @type {MomentCommentInfo[]}
             */
            this["comments"] = [];
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MomentInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MomentInfo}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField3_0($$parsedSource["images"]);
        }
        if ("likes" in $$parsedSource) {
            $$parsedSource["likes"] = $$createField4_0($$parsedSource["likes"]);
        }
        if ("comments" in $$parsedSource) {
            $$parsedSource["comments"] = $$createField5_0($$parsedSource["comments"]);
        }
        return new MomentInfo(/** @type {Partial<MomentInfo>} */($$parsedSource));
    }
}

export class Profile {
    /**
     * Creates a new Profile instance.
     * @param {Partial<Profile>} [$$source = {}] - The source object to create the Profile.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("avatar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatar"] = "";
        }
        if (!("gender" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gender"] = 0;
        }
        if (!("birthday" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["birthday"] = "";
        }
        if (!("signature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["signature"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("phone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phone"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Profile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile(/** @type {Partial<Profile>} */($$parsedSource));
    }
}

export class RegisterResult {
    /**
     * Creates a new RegisterResult instance.
     * @param {Partial<RegisterResult>} [$$source = {}] - The source object to create the RegisterResult.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegisterResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RegisterResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RegisterResult(/** @type {Partial<RegisterResult>} */($$parsedSource));
    }
}

export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("profile" in $$source)) {
            /**
             * 序列化的 JSON 字符串
             * @member
             * @type {string}
             */
            this["profile"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

export class UserBriefInfo {
    /**
     * Creates a new UserBriefInfo instance.
     * @param {Partial<UserBriefInfo>} [$$source = {}] - The source object to create the UserBriefInfo.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("avatar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatar"] = "";
        }
        if (!("gender" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gender"] = 0;
        }
        if (!("signature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["signature"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserBriefInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserBriefInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserBriefInfo(/** @type {Partial<UserBriefInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = MomentCommentInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
