// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LoginResult {
    /**
     * Creates a new LoginResult instance.
     * @param {Partial<LoginResult>} [$$source = {}] - The source object to create the LoginResult.
     */
    constructor($$source = {}) {
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoginResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginResult(/** @type {Partial<LoginResult>} */($$parsedSource));
    }
}

export class Profile {
    /**
     * Creates a new Profile instance.
     * @param {Partial<Profile>} [$$source = {}] - The source object to create the Profile.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("avatar" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["avatar"] = "";
        }
        if (!("gender" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gender"] = 0;
        }
        if (!("birthday" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["birthday"] = "";
        }
        if (!("signature" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["signature"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("phone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phone"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Profile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Profile(/** @type {Partial<Profile>} */($$parsedSource));
    }
}

export class RegisterResult {
    /**
     * Creates a new RegisterResult instance.
     * @param {Partial<RegisterResult>} [$$source = {}] - The source object to create the RegisterResult.
     */
    constructor($$source = {}) {
        if (!("uid" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RegisterResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RegisterResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RegisterResult(/** @type {Partial<RegisterResult>} */($$parsedSource));
    }
}
